name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate 3D contribution calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          committer_token: ${{ github.token }}
          committer_branch: main
          committer_message: "chore: update contribution calendar"
          output_action: commit

          user: aditya-kg
          filename: assets/metrics.isocalendar.svg

          base: ""
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugins_errors_fatal: yes
