name: GitHub-User-Statistician

on:
  schedule:
    - cron: "30 21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-stats-svg

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate GitHub stats SVG
        uses: cicirello/user-statistician@v1
        with:
          image-file: github-user-stats.svg
          colors: dark
          include-title: true
          custom-title: "GitHub Statistics"
          show-border: true
          border-radius: 8
          animated-language-chart: true
          language-animation-speed: 12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
